"""
AUTOGENERATED by demo2rules.py
Dataset : Hafnium49/aloha_lite  (episode 1)
SHA‑256 : fc327fe0e0
Params  : {"dataset":"Hafnium49/aloha_lite","episode":1,"out":"rules_episode_1.py","vel_thresh":0.03,"window":15,"left_arm":"so101_left","right_arm":"so101_right","ruleset_name":"so101_dual","single_arm":false}
"""

from durable.lang import *
from phosphobot import SkillClient

left_arm  = SkillClient("so101_left")
right_arm = SkillClient("so101_right")

with ruleset("so101_dual"):

    @when_all(+m.ready)
    def _start(c):
        c.post({"stage": 0})


    @when_all(m.stage == 0)
    def stage_0(c):
        # joints
        left_arm.move_j([0.17184780538082123, -1.8642418384552002, 1.459172010421753, -1.7568368911743164, -1.3824541568756104, 0.7871243357658386])
        right_arm.move_j([0.37898579239845276, -1.8044019937515259, 1.4392253160476685, -1.7553025484085083, -1.614141821861267, 1.5803860425949097])
        # cartesian (optional)

        # grippers
        # no gripper info
        c.post({"stage": 1})

    @when_all(m.stage == 1)
    def stage_1(c):
        # joints
        left_arm.move_j([0.17184780538082123, -1.8642418384552002, 1.459172010421753, -1.7568368911743164, -1.3824541568756104, 0.7871243357658386])
        right_arm.move_j([0.37898579239845276, -1.8044019937515259, 1.4131413698196411, -1.7553025484085083, -1.614141821861267, 1.5803860425949097])
        # cartesian (optional)

        # grippers
        # no gripper info
        c.post({"stage": 2})

    @when_all(m.stage == 2)
    def stage_2(c):
        # joints
        left_arm.move_j([0.17184780538082123, -1.8642418384552002, 1.459172010421753, -1.7568368911743164, -1.3824541568756104, 0.7871243357658386])
        right_arm.move_j([0.37898579239845276, -1.8044019937515259, 1.4131413698196411, -1.7553025484085083, -1.614141821861267, 1.5803860425949097])
        # cartesian (optional)

        # grippers
        # no gripper info
        c.post({"stage": 3})


    @when_all(m.stage == 3)
    def _done(c):
        print("🎉  demo finished")
